version: "3.8"

services:
  backend:
    build:
      context: ./api
    ports:
      - "5000:5000"
    env_file:
      - .env  # Chỉ định tệp .env mà Docker sẽ sử dụng
    environment:
      - PORT=5000
      - MONGO_URL=mongodb://mongo:27017/mydb
    depends_on:
      - mongo

  frontend:
    build:
      context: ./solution
    ports:
      - "3000:80"
    container_name: frontend
    restart: unless-stopped

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: